name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  playwright-runner:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright UI Tests
        run: |
          yarn cucumber-js || exit 1
          node ./htmlReport.js || exit 1

      - name: Upload UI Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: UI Report
          path: Reports/
          retention-days: 30

      - name: Run Playwright API Tests
        run: yarn run api

      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: API Report
          path: Reports/
          retention-days: 30
