name: Playwright Blog Tests
on: [push]
jobs:
  playwright-runner:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright API Tests
        run: pnpm api
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: API Report
          path: Report/api_report.json
          retention-days: 30

      - name: Run Playwright UI Tests
        run: pnpm ui
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: UI Report
          path: Reports/cucumber_report_*.html
          retention-days: 30
